### ISSUE TITLE
mysqladmin and other tools missing from mysql:8

### ISSUE THREAD

**Issue by stealthybox** [docker-library/mysql#410]
Hi 👋 

The recent tag move for `latest` -> `8` started failing our kubernetes liveness probes:

`Liveness:   exec [mysqladmin ping --host 127.0.0.1 --port 3306] delay=5s timeout=5s period=10s #success=1 #failure=3`

The mysql docs suggest that this tool should be usable with both MySQL 5.7 and 8.0:
- https://dev.mysql.com/doc/refman/5.7/en/mysqladmin.html
- https://dev.mysql.com/doc/refman/8.0/en/mysqladmin.html

It seems there may be other tools missing from the `mysql:8` image as well:
```bash
comm \
<(docker run --entrypoint sh -w /usr/bin mysql:5 -c 'ls mysql*') \
<(docker run --entrypoint sh -w /usr/bin mysql:8 -c 'ls mysql*')

		mysql
mysql_config_editor
mysql_embedded
mysql_install_db
mysql_plugin
		mysql_secure_installation
		mysql_ssl_rsa_setup
		mysql_tzinfo_to_sql
		mysql_upgrade
mysqladmin
		mysqlbinlog
mysqlcheck
		mysqld_multi
		mysqld_safe
		mysqldump
mysqldumpslow
mysqlimport
		mysqlpump
mysqlshow
mysqlslap
```

Cheers

**Comment by ltangvald** [comment]
Hi,

This is an oversight in our server-core packages, sorry. The contents of the package are listed in https://github.com/mysql/mysql-server/blob/8.0/packaging/deb-in/mysql-packagesource-server-core.install.in

We did drop some of the executables from the core package, since we don't consider them necessary for most people, but mysqladmin should be there (it's in the minimal rpm used for the upstream docker image)

**Comment by stealthybox** [comment]
@ltangvald thanks for the reference.

Will `mysqladmin` be added back into the debian package?
I currently don't see it in that install file unless I'm missing something implicit.

**Comment by tianon** [comment]
Essentially https://github.com/mysql/mysql-server/commit/625609bbb9034007f498d40d5c337e9bc3a2ae87, but to add `mysqladmin`? :sweat_smile:

**Comment by stealthybox** [comment]
@tianon aha! yeah 😅

**Comment by Coolfeather2** [comment]
got same problem, waiting for new release

**Comment by falcoschwarz** [comment]
Please also add back mysql_config_editor. It was such an elegant way to not store any passwords in clear text.

**Comment by toolowner** [comment]
Still waiting for mysqladmin :clock1:

**Comment by ltangvald** [comment]
@toolowner: That's my mistake, sorry. It fell through the cracks. However, there isn't really much need to use the client-core package since the only difference is that these extra binaries are missing.
I've made PR #465, which should resolve this.

**Comment by tianon** [comment]
Fixed by https://github.com/docker-library/mysql/pull/465. :+1:

**Comment by stealthybox** [comment]
@tianon I'm curious
will this patch auto-build tonight?
last push was 3 days ago: https://hub.docker.com/r/library/mysql/tags/

(unit test still fails)
```bash
comm \
<(docker run --entrypoint sh -w /usr/bin mysql:5 -c 'ls mysql*') \
<(docker run --entrypoint sh -w /usr/bin mysql:8 -c 'ls mysql*')
```

thanks very much!

**Comment by Coolfeather2** [comment]
when he creates a pull request https://github.com/docker-library/official-images/issues?&q=label%3Alibrary%2Fmysql

**Comment by stealthybox** [comment]
ah thanks @Coolfeather2
